### ISSUE TITLE
CRAN

### ISSUE THREAD

**Issue by hadley** [teramonagi/RODBCDBI#3]
Can I do anything to help this package get to CRAN? I think a lot of people would appreciate it.

**Comment by teramonagi** [comment]
Thank you for your advice.
That sounds good because I originally created this package to be `dplyr` compatible one at first based on your comment(http://comments.gmane.org/gmane.comp.lang.r.manipulatr/930)

My main issue is "unit test" because the on-line CI tool like "travis-ci" does not seem to have strong windows(ODBC) support. I do not have any idea about that.

And the other issues which you reported sounds reasonable, I will fix it !!!

**Comment by hadley** [comment]
Have you looked into appveyor?

**Comment by teramonagi** [comment]
This service completely meets my needs.
- http://www.appveyor.com/

I will try it!

**Comment by teramonagi** [comment]
This package was uploaded on CRAN!!!
- https://cran.r-project.org/web/packages/RODBCDBI/index.html

Thanks you for your advice anyway :+1:

**Comment by hadley** [comment]
Great!

**Comment by teramonagi** [comment]
@hadley 

Let me ask you a one question to you.
I want to hear your opinion about whether I can talk this package(and additional theme) and how to develop and upload a package on CRAN in useR! conference 2016.
Is it a good theme for useR! conference?

Actually speaking, I'm looking for a good reason to go to useR! and explain why I should do that to my boss...

**Comment by hadley** [comment]
Yes, this would be a great talk!
